### ISSUE TITLE
  File "/home/mona/Unseen_Object_Pose/Render/data_generation.py", line 138, in src_image_generate     _, depth = render_objects([meshes[int(key.split('_')[0])-1]], [0], [pose], dst_K, \ NameError: name 'render_objects' is not defined

### ISSUE THREAD

**Issue by monajalal** [sailor-z/Unseen_Object_Pose#6]
It seems there is an error in data_generation.py
Could you please suggest a fix patch?
```
(testbpy) mona@ard-gpu-01:~/Unseen_Object_Pose/Render$ python data_generation.py
WARN (bgl): source/blender/python/generic/bgl.c:2654 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
---------- image generation------------
Generating src image for 000001
  0%|                                                                                                                                                                                      | 0/185 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mona/Unseen_Object_Pose/Render/data_generation.py", line 226, in <module>
    src_image_generate(cfg, 'train')
  File "/home/mona/Unseen_Object_Pose/Render/data_generation.py", line 138, in src_image_generate
    _, depth = render_objects([meshes[int(key.split('_')[0])-1]], [0], [pose], dst_K, \
NameError: name 'render_objects' is not defined
```

**Comment by monajalal** [comment]
fixed details here https://github.com/TylerGubala/blenderpy/issues/135#issuecomment-1513672739
